function rays = ray_tracingEx(file_path, rx_pos, maxReflections, numOfDiff, freq)
% ray_tracing -- is a function to return the rays generated by the ray-tracing propagation model of matlab for the  
%
% ==============Arguments=====================
%
%    - file_path: the name of the stl file map to run the ray-tracing model
%    on
%
%    - rx_ant: a cell array to contain => 1) the rx_antenna, 2) the
%    position of the rx_antenna
% ==============Return=======================
%
%    - rays: the rays returned from =>  raytrace()
%

    %% map

    TR = stlread(file_path); %reading the stl file ( triangulation object )
    
    viewer = siteviewer("SceneModel",TR); % insertion of the surface/reflector in the cartesian system

    %% init consts
    fc = freq; % antenna frequency 
    c = physconst("Lightspeed");
    lambda = c/fc;

    %% tx-site
    tx_antenna = horn("FlareLength",0.196,"FlareWidth",0.118,"FlareHeight",0.105);% transmitter horn antenna
    tx_pos = [-2.2; 4; 1.75]; % transmiter antenna position
    tx_angles = txAntSteerCopyPaste(tx_pos, [ 0 0 0 ]);

    % creation of transmitter site
    tx = txsite("cartesian", ...
        "AntennaPosition",tx_pos, ...
        "TransmitterFrequency",fc,...
        "Antenna",tx_antenna,...
        "TransmitterPower",0.001);
    tx.AntennaAngle = tx_angles; % azimuth and elevation angles in order for the antenna to "look" at => (0,0,0)
    show(tx,"ShowAntennaHeight",false) 
    
    %pattern(tx);
    
    %% rx-site
    
    % center_pos = [-2; 2; 1.4];
    % rx_dim=[3 3];
    % rx_pos = getRxPos(rx_dim, fc, center_pos);
    
    rx = rxsite("cartesian", ...,
        "AntennaPosition", rx_pos);
    show(rx,"ShowAntennaHeight",false)
    
    %% propagation model and raytracing
    % creation of the propagation model
    pm = propagationModel("raytracing", ...
        "CoordinateSystem","cartesian", ...
        "Method","sbr", ...
        "AngularSeparation","medium",...
        "MaxNumReflections",1+maxReflections, ...
        "MaxNumDiffractions",numOfDiff,...
        "SurfaceMaterial","perfect-reflector"); 
    
    % use of ray-tracing model 
    rays = raytrace(tx,rx,pm);

    close(viewer);
    

end